### ISSUE TITLE
ImportError when trying to run Demo: ImportError: Missing optional dependency 'lxml'

### ISSUE THREAD

**Issue by pettyalex** [nhgritctran/PheTK#2]
I installed PheTK `v0.1.38` from PyPI today and attempted to run the demo, which failed immediately. It looks like lxml needs to be added as a dependency.

Python version: 3.9.16
OS version: Mac OS 14.4.1
Macbook Air M1, 2020, 16GB RAM

Inputs were:
```
Which data type would you like the variable of interest to be? (binary/continuous) binary
Would you like data to have both sexes? (yes/no) yes
```

Immediately when the demo attempted to run the phewas I see:
```
Press enter to run PheWAS!

~~~~~~~~~~~~~~~~~~~~~~~~    Creating PheWAS Object    ~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~    Running PheWAS    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  0%|                                                                                        | 0/461 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lxml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/Demo.py", line 185, in <module>
    run()
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/Demo.py", line 173, in run
    phewas.run()
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/PheWAS.py", line 477, in run
    result_dicts = [job.result() for job in tqdm(as_completed(jobs), total=len(self.phecode_list))]
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/PheWAS.py", line 477, in <listcomp>
    result_dicts = [job.result() for job in tqdm(as_completed(jobs), total=len(self.phecode_list))]
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/PheWAS.py", line 438, in _logistic_regression
    stats_dict = self._result_prep(result=result, var_of_interest_index=var_index)
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/PheTK/PheWAS.py", line 351, in _result_prep
    converged = pd.read_html(results_as_html)[0].iloc[5, 1]
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/pandas/io/html.py", line 1240, in read_html
    return _parse(
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/pandas/io/html.py", line 971, in _parse
    parser = _parser_dispatch(flav)
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/pandas/io/html.py", line 918, in _parser_dispatch
    import_optional_dependency("lxml.etree")
  File "/Users/alex/scratch/phetk/venv/lib/python3.9/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.
  0%|                                                                                        | 0/461 [00:08<?, ?it/s]
```

A complete list of installed python packages is:
```
adjustText==1.1.1
aiodns==2.0.0
aiohttp==3.9.5
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.2.0
autograd==1.6.2
autograd-gamma==0.5.0
avro==1.11.3
azure-common==1.1.28
azure-core==1.30.1
azure-identity==1.16.0
azure-mgmt-core==1.4.0
azure-mgmt-storage==20.1.0
azure-storage-blob==12.19.1
bokeh==3.4.1
boto3==1.34.96
botocore==1.34.96
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
commonmark==0.9.1
connectorx==0.3.2
contourpy==1.2.1
cryptography==42.0.5
cycler==0.12.1
decorator==4.4.2
Deprecated==1.2.14
dill==0.3.8
fonttools==4.51.0
formulaic==1.0.1
frozenlist==1.4.1
future==1.0.0
google-api-core==2.19.0
google-auth==2.29.0
google-auth-oauthlib==0.8.0
google-cloud-bigquery==3.21.0
google-cloud-core==2.4.1
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.63.0
grpcio==1.63.0
grpcio-status==1.62.2
hail==0.2.130
humanize==1.1.0
idna==3.7
importlib_resources==6.4.0
interface-meta==1.3.0
isodate==0.6.1
janus==1.0.0
Jinja2==3.1.3
jmespath==1.0.1
jproperties==2.1.1
kiwisolver==1.4.5
lifelines==0.28.0
MarkupSafe==2.1.5
matplotlib==3.8.4
msal==1.28.0
msal-extensions==1.1.0
msrest==0.7.1
multidict==6.0.5
nest-asyncio==1.6.0
numpy==1.26.4
oauthlib==3.2.2
orjson==3.9.10
packaging==24.0
pandas==2.2.2
parsimonious==0.10.0
patsy==0.5.6
PheTK==0.1.38
pillow==10.3.0
plotly==5.22.0
polars==0.20.23
portalocker==2.8.2
proto-plus==1.23.0
protobuf==4.25.3
py4j==0.10.9.5
pyarrow==16.0.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycares==4.4.0
pycparser==2.22
Pygments==2.17.2
PyJWT==2.8.0
pyparsing==3.1.2
pyspark==3.3.4
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.1
PyYAML==6.0.1
regex==2024.4.28
requests==2.31.0
requests-oauthlib==2.0.0
rich==12.6.0
rsa==4.9
s3transfer==0.10.1
scipy==1.11.4
shellingham==1.5.4
six==1.16.0
sortedcontainers==2.4.0
statsmodels==0.14.2
tabulate==0.9.0
tenacity==8.2.3
tornado==6.4
tqdm==4.66.2
typer==0.12.3
typing_extensions==4.11.0
tzdata==2024.1
urllib3==1.26.18
uvloop==0.19.0
wrapt==1.16.0
xyzservices==2024.4.0
yarl==1.9.4
zipp==3.18.1
```

**Comment by nhgritctran** [comment]
Thank you for letting me know. You are correct. lxml is a dependency for pandas used for a result processing step. I will add it as a dependency in the next release.

**Comment by pettyalex** [comment]
The cleanest way to do this might be to specify pandas optional dependencies: https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies

Given that the install is huge already you might as well do `pandas[all]`, but if you wanted only lxml you could do `pandas[xml]`

**Comment by nhgritctran** [comment]
`Pandas` is used only for few steps where other dependencies do not support `polars` yet. Therefore, installing all `pandas` dependencies is redundant.

As of now, I believe simply running `pip install lxml` and restarting terminal/notebook kernel should fix it. There is no need to make changes to PheTK installation.

The installation might feel "huge" mainly due to `hail`, a dependency for Cohort module. `hail` usually comes preinstalled on platforms that supports it, e.g., _All of Us_ researcher workbench dataproc VMs. That said, the installation on other platforms should not take long at all.

**Comment by pettyalex** [comment]
> As of now, lxml is not installed in your work environment yet, I believe simply running pip install lxml and restarting terminal/notebook kernel should fix it. There is no need to make changes to PheTK installation.

If you update your requirement on `pandas` to include `pandas[xml]` then it will work out of the box, without any additional steps, which would be a better experience for users of this tool.

**Comment by nhgritctran** [comment]
> > As of now, lxml is not installed in your work environment yet, I believe simply running pip install lxml and restarting terminal/notebook kernel should fix it. There is no need to make changes to PheTK installation.
> 
> 
> 
> If you update your requirement on `pandas` to include `pandas[xml]` then it will work out of the box, without any additional steps, which would be a better experience for users of this tool.
> 
> 
> 
> 

Agreed - lxml will be added as mentioned in my intial comment. I misunderstood your previous comment as a solution for your own use case.

**Comment by nhgritctran** [comment]
Closing thread as lxml was added in version 0.1.39.
